name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AI PR Review
        uses: vadim-heyworld/pr-review-action@v0.2.6-alpha
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          project-name: 'tms'
          openai-model: 'gpt-4o'
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.APP_INSTALLATION_ID }}
